<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="shortcut icon" href="../../../img/favicon.ico" />
    <title>2D Rectangle - Build123d Noob help</title>
    <link rel="stylesheet" href="../../../css/theme.css" />
    <link rel="stylesheet" href="../../../css/theme_extra.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css" />
    
      <script>
        // Current page data
        var mkdocs_page_name = "2D Rectangle";
        var mkdocs_page_input_path = "Function description\\2D Objects\\2D Rectangle.md";
        var mkdocs_page_url = null;
      </script>
    
    <!--[if lt IE 9]>
      <script src="../../../js/html5shiv.min.js"></script>
    <![endif]-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
      <script>hljs.highlightAll();</script> 
</head>

<body class="wy-body-for-nav" role="document">

  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side stickynav">
    <div class="wy-side-scroll">
      <div class="wy-side-nav-search">
          <a href="../../.." class="icon icon-home"> Build123d Noob help
        </a><div role="search">
  <form id ="rtd-search-form" class="wy-form" action="../../../search.html" method="get">
      <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" title="Type search term here" />
  </form>
</div>
      </div>

      <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul>
                <li class="toctree-l1"><a class="reference internal" href="../../../Index/">Welcome to build123d noob help</a>
                </li>
              </ul>
              <p class="caption"><span class="caption-text">Function description</span></p>
              <ul class="current">
                  <li class="toctree-l1"><a class="reference internal" href="#">1D Objects</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../1D%20Objects/1D%20Line/">1D Line</a>
                </li>
    </ul>
                  </li>
                  <li class="toctree-l1 current"><a class="reference internal current" href="#">2D Objects</a>
    <ul class="current">
                <li class="toctree-l2 current"><a class="reference internal current" href="./">2D Rectangle</a>
    <ul class="current">
    </ul>
                </li>
    </ul>
                  </li>
              </ul>
              <p class="caption"><span class="caption-text">Setup of the working enviroment</span></p>
              <ul>
                  <li class="toctree-l1"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/">Testtitle</a>
                  </li>
                  <li class="toctree-l1"><a class="reference internal" href="#">MkDocs Installation</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/MkDocs%20Installation/MkDocs%20portable%20Installation/">MkDocs portable Installation</a>
                </li>
    </ul>
                  </li>
                  <li class="toctree-l1"><a class="reference internal" href="#">Visual Studio Code Setup</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/OCP%20Viewer%20adjustments/">OCP Viewer adjustments</a>
                </li>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/Visual%20Studio%20Code%20Windows%20Portable%20Setup%20for%20build123d/">Visual Studio Code Windows Portable Setup for build123d</a>
                </li>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/Visual%20Studio%20Code%20extensions%20or%20adjustments/">Visual Studio Code extensions or adjustments</a>
                </li>
    </ul>
                  </li>
              </ul>
      </div>
    </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">
      <nav class="wy-nav-top" role="navigation" aria-label="Mobile navigation menu">
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../..">Build123d Noob help</a>
        
      </nav>
      <div class="wy-nav-content">
        <div class="rst-content"><div role="navigation" aria-label="breadcrumbs navigation">
  <ul class="wy-breadcrumbs">
    <li><a href="../../.." class="icon icon-home" aria-label="Docs"></a></li>
          <li class="breadcrumb-item">Function description</li>
          <li class="breadcrumb-item">2D Objects</li>
      <li class="breadcrumb-item active">2D Rectangle</li>
    <li class="wy-breadcrumbs-aside">
    </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
            <div class="section" itemprop="articleBody">
              
                <h2 id="rectangle-of-lines">Rectangle of Lines</h2>
<p>```python linenums="1"</p>
<h1 id="import-ocp_vscode-which-is-an-addon-to-view-the-3d-model-in-vscode">Import ocp_vscode which is an addon to view the 3D model in VScode</h1>
<p>from ocp_vscode import *</p>
<h1 id="import-build123d-library-to-be-able-to-use-build123-commands">Import build123d library to be able to use build123 commands</h1>
<p>from build123d import *</p>
<h1 id="define-an-x-and-y-value-for-the-rectangle">Define an x and y value for the rectangle</h1>
<p>x=20
y=10</p>
<h1 id="start-the-sketch-builder-which-creates-2d-sketch-objects">Start the Sketch builder which creates 2D sketch objects</h1>
<p>with BuildSketch() as RectangleAsSketch:
  # Start the Line Builder and define the name of the finished line object as RectangleOfLines
  with BuildLine() as RectangleOfLines:
    # Define first line
    Line((0,0),(x,0))
    # Define second line
    Line((x,0),(x,y))
    # Define third line
    Line((x,y),(0,y))
    # Define fourth and last line to close the rectangle shape
    Line((0,y),(0,0))
  # Create a face from your RectangleOfLines object. Lines must be closed to encompass a closed area.
  make_face()</p>
<h1 id="show-all-created-objects-which-is-only-rectangleoflines">Show all created objects which is only RectangleOfLines</h1>
<p>show_all()</p>
<pre><code>
This creates a 2D sketch and a new object RectangleAsSketch. This sketch can be extruded to get a 3D object.

See: 3D Box

## 2D Rectangle

```python linenums=&quot;1&quot;
# Import ocp_vscode which is an addon to view the 3D model in VScode
from ocp_vscode import *
# Import build123d library to be able to use build123 commands
from build123d import *

# Define an x and y value for the rectangle
x=20
y=10

# Start the Sketch builder which creates 2D sketch objects
with BuildSketch() as RectangleAsSketch:
  Rectangle(x,y)

# Show all created objects which is only RectangleOfLines
show_all()
</code></pre>
<p>This gives the same sketch object as the one we created with RectangleOfLines. You might notice that we needed less information AND that this object will now be centered at the origin (x=0,y=0). All objects will normally be build by being centered as each object has an additional property called "alignt" which has as default the center option. So to make it truly equal we have to adjust it's placing.</p>
<h2 id="placing-with-align">Placing with "align"</h2>
<p>``` python linenums="1"</p>
<h1 id="import-ocp_vscode-which-is-an-addon-to-view-the-3d-model-in-vscode_1">Import ocp_vscode which is an addon to view the 3D model in VScode</h1>
<p>from ocp_vscode import *</p>
<h1 id="import-build123d-library-to-be-able-to-use-build123-commands_1">Import build123d library to be able to use build123 commands</h1>
<p>from build123d import *</p>
<h1 id="define-an-x-and-y-value-for-the-rectangle_1">Define an x and y value for the rectangle</h1>
<p>x=20
y=10</p>
<h1 id="start-the-sketch-builder-which-creates-2d-sketch-objects_1">Start the Sketch builder which creates 2D sketch objects</h1>
<p>with BuildSketch() as RectangleAsSketch:
  # Create a Rectangle and change it's alignment property
  Rectangle(x,y,align=(Align.MIN,Align.MIN))</p>
<h1 id="show-all-created-objects-which-is-only-rectangleoflines_1">Show all created objects which is only RectangleOfLines</h1>
<p>show_all()
```</p>
<p>The "align=" options you can choose from are:</p>
<ul>
<li>Align.MIN</li>
<li>Align.MAX</li>
<li>Align.CENTER</li>
</ul>
<p>You can use each of these options for one of the 2 paramters of the "align=" statement.</p>
<h2 id="placing-with-the-position-property-of-the-object">Placing with the position property of the object</h2>
<h2 id="placing-with-the-pos-command">Placing with the POS() command</h2>
<h2 id="other-options-to-create-a-rectangle-or-a-edged-2d-shape">Other options to create a rectangle or a edged 2D shape</h2>
<p>Other ways to create a rectangle is to use the Rectangle, Polygon,  RegularPolygon or Trapezoid.</p>
<p>See: Polygon</p>
<p>See: RegularPolygon</p>
<p>See: Trapezoid</p>
              
            </div>
          </div><footer>
    <div class="rst-footer-buttons" role="navigation" aria-label="Footer Navigation">
        <a href="../../1D%20Objects/1D%20Line/" class="btn btn-neutral float-left" title="1D Line"><span class="icon icon-circle-arrow-left"></span> Previous</a>
        <a href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/" class="btn btn-neutral float-right" title="Testtitle">Next <span class="icon icon-circle-arrow-right"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <!-- Copyright etc -->
  </div>

  Built with <a href="https://www.mkdocs.org/">MkDocs</a> using a <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>.
</footer>
          
        </div>
      </div>

    </section>

  </div>

  <div class="rst-versions" role="note" aria-label="Versions">
  <span class="rst-current-version" data-toggle="rst-current-version">
    
    
      <span><a href="../../1D%20Objects/1D%20Line/" style="color: #fcfcfc">&laquo; Previous</a></span>
    
    
      <span><a href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/" style="color: #fcfcfc">Next &raquo;</a></span>
    
  </span>
</div>
    <script src="../../../js/jquery-3.6.0.min.js"></script>
    <script>var base_url = "../../..";</script>
    <script src="../../../js/theme_extra.js"></script>
    <script src="../../../js/theme.js"></script>
      <script src="../../../search/main.js"></script>
    <script>
        jQuery(function () {
            SphinxRtdTheme.Navigation.enable(true);
        });
    </script>

</body>
</html>
