<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><link rel="canonical" href="https://github.com/CePeU/build123-for-noobs/Function%20description/2D%20Objects/2D%20Rectangle/" />
      <link rel="shortcut icon" href="../../../img/favicon.ico" />
    <title>2D Rectangle - Build123d Noob help</title>
    <link rel="stylesheet" href="../../../css/theme.css" />
    <link rel="stylesheet" href="../../../css/theme_extra.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css" />
    
      <script>
        // Current page data
        var mkdocs_page_name = "2D Rectangle";
        var mkdocs_page_input_path = "Function description\\2D Objects\\2D Rectangle.md";
        var mkdocs_page_url = "/CePeU/build123-for-noobs/Function%20description/2D%20Objects/2D%20Rectangle/";
      </script>
    
    <!--[if lt IE 9]>
      <script src="../../../js/html5shiv.min.js"></script>
    <![endif]-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
      <script>hljs.highlightAll();</script> 
</head>

<body class="wy-body-for-nav" role="document">

  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side stickynav">
    <div class="wy-side-scroll">
      <div class="wy-side-nav-search">
          <a href="../../.." class="icon icon-home"> Build123d Noob help
        </a><div role="search">
  <form id ="rtd-search-form" class="wy-form" action="../../../search.html" method="get">
      <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" title="Type search term here" />
  </form>
</div>
      </div>

      <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul>
                <li class="toctree-l1"><a class="reference internal" href="../../../Index/">Index</a>
                </li>
              </ul>
              <ul>
                <li class="toctree-l1"><a class="reference internal" href="../../../Readme/">Readme</a>
                </li>
              </ul>
              <p class="caption"><span class="caption-text">Function description</span></p>
              <ul class="current">
                  <li class="toctree-l1"><a class="reference internal" href="#">1D Objects</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../1D%20Objects/1D%20Line/">1D Line</a>
                </li>
    </ul>
                  </li>
                  <li class="toctree-l1 current"><a class="reference internal current" href="#">2D Objects</a>
    <ul class="current">
                <li class="toctree-l2 current"><a class="reference internal current" href="./">2D Rectangle</a>
    <ul class="current">
    </ul>
                </li>
    </ul>
                  </li>
              </ul>
              <p class="caption"><span class="caption-text">Setup of the working enviroment</span></p>
              <ul>
                  <li class="toctree-l1"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/">Testtitle</a>
                  </li>
                  <li class="toctree-l1"><a class="reference internal" href="#">MkDocs Installation</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/MkDocs%20Installation/MkDocs%20portable%20Installation/">MkDocs portable Installation</a>
                </li>
    </ul>
                  </li>
                  <li class="toctree-l1"><a class="reference internal" href="#">Visual Studio Code Setup</a>
    <ul>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/OCP%20Viewer%20adjustments/">OCP Viewer adjustments</a>
                </li>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/OCP%20Viewer%20setup/">OCP Viewer setup</a>
                </li>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/Visual%20Studio%20Code%20Windows%20Portable%20Setup%20for%20build123d/">Visual Studio Code Windows Portable Setup for build123d</a>
                </li>
                <li class="toctree-l2"><a class="reference internal" href="../../../Setup%20of%20the%20working%20enviroment/Visual%20Studio%20Code%20Setup/Visual%20Studio%20Code%20extensions%20or%20adjustments/">Visual Studio Code extensions or adjustments</a>
                </li>
    </ul>
                  </li>
              </ul>
      </div>
    </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">
      <nav class="wy-nav-top" role="navigation" aria-label="Mobile navigation menu">
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../..">Build123d Noob help</a>
        
      </nav>
      <div class="wy-nav-content">
        <div class="rst-content"><div role="navigation" aria-label="breadcrumbs navigation">
  <ul class="wy-breadcrumbs">
    <li><a href="../../.." class="icon icon-home" aria-label="Docs"></a></li>
          <li class="breadcrumb-item">Function description</li>
          <li class="breadcrumb-item">2D Objects</li>
      <li class="breadcrumb-item active">2D Rectangle</li>
    <li class="wy-breadcrumbs-aside">
    </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
            <div class="section" itemprop="articleBody">
              
                <h3 id="rectangle-of-lines">Rectangle of Lines</h3>
<div class="highlight"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span></span><span class="normal"> 1</span>
<span class="normal"> 2</span>
<span class="normal"> 3</span>
<span class="normal"> 4</span>
<span class="normal"> 5</span>
<span class="normal"> 6</span>
<span class="normal"> 7</span>
<span class="normal"> 8</span>
<span class="normal"> 9</span>
<span class="normal">10</span>
<span class="normal">11</span>
<span class="normal">12</span>
<span class="normal">13</span>
<span class="normal">14</span>
<span class="normal">15</span>
<span class="normal">16</span>
<span class="normal">17</span>
<span class="normal">18</span>
<span class="normal">19</span>
<span class="normal">20</span>
<span class="normal">21</span>
<span class="normal">22</span>
<span class="normal">23</span>
<span class="normal">24</span>
<span class="normal">25</span>
<span class="normal">26</span></pre></div></td><td class="code"><div><pre><span></span><code><span class="c1"># Import ocp_vscode which is an addon to view the 3D model in VScode</span>
<span class="kn">from</span> <span class="nn">ocp_vscode</span> <span class="kn">import</span> <span class="o">*</span>
<span class="c1"># Import build123d library to be able to use build123 commands</span>
<span class="kn">from</span> <span class="nn">build123d</span> <span class="kn">import</span> <span class="o">*</span>

<span class="c1"># Define an x and y value for the rectangle</span>
<span class="n">x</span><span class="o">=</span><span class="mi">20</span>
<span class="n">y</span><span class="o">=</span><span class="mi">10</span>

<span class="c1"># Start the Sketch builder which creates 2D sketch objects</span>
<span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">RectangleAsSketch</span><span class="p">:</span>
  <span class="c1"># Start the Line Builder and define the name of the finished line object as RectangleOfLines</span>
  <span class="k">with</span> <span class="n">BuildLine</span><span class="p">()</span> <span class="k">as</span> <span class="n">RectangleOfLines</span><span class="p">:</span>
    <span class="c1"># Define first line</span>
    <span class="n">Line</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">),(</span><span class="n">x</span><span class="p">,</span><span class="mi">0</span><span class="p">))</span>
    <span class="c1"># Define second line</span>
    <span class="n">Line</span><span class="p">((</span><span class="n">x</span><span class="p">,</span><span class="mi">0</span><span class="p">),(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">))</span>
    <span class="c1"># Define third line</span>
    <span class="n">Line</span><span class="p">((</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">),(</span><span class="mi">0</span><span class="p">,</span><span class="n">y</span><span class="p">))</span>
    <span class="c1"># Define fourth and last line to close the rectangle shape</span>
    <span class="n">Line</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span><span class="n">y</span><span class="p">),(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">))</span>
  <span class="c1"># Create a face from your RectangleOfLines object. Lines must be closed to encompass a closed area.</span>
  <span class="n">make_face</span><span class="p">()</span>

<span class="c1"># Show all created objects which is only RectangleOfLines</span>
<span class="n">show_all</span><span class="p">()</span>
</code></pre></div></td></tr></table></div>
<p>This creates a 2D sketch and a new object RectangleAsSketch. This sketch can be extruded to get a 3D object.</p>
<p>See: 3D Box</p>
<h3 id="2d-rectangle">2D Rectangle</h3>
<div class="highlight"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span></span><span class="normal"> 1</span>
<span class="normal"> 2</span>
<span class="normal"> 3</span>
<span class="normal"> 4</span>
<span class="normal"> 5</span>
<span class="normal"> 6</span>
<span class="normal"> 7</span>
<span class="normal"> 8</span>
<span class="normal"> 9</span>
<span class="normal">10</span>
<span class="normal">11</span>
<span class="normal">12</span>
<span class="normal">13</span>
<span class="normal">14</span>
<span class="normal">15</span></pre></div></td><td class="code"><div><pre><span></span><code><span class="c1"># Import ocp_vscode which is an addon to view the 3D model in VScode</span>
<span class="kn">from</span> <span class="nn">ocp_vscode</span> <span class="kn">import</span> <span class="o">*</span>
<span class="c1"># Import build123d library to be able to use build123 commands</span>
<span class="kn">from</span> <span class="nn">build123d</span> <span class="kn">import</span> <span class="o">*</span>

<span class="c1"># Define an x and y value for the rectangle</span>
<span class="n">x</span><span class="o">=</span><span class="mi">20</span>
<span class="n">y</span><span class="o">=</span><span class="mi">10</span>

<span class="c1"># Start the Sketch builder which creates 2D sketch objects</span>
<span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">RectangleAsSketch</span><span class="p">:</span>
  <span class="n">Rectangle</span><span class="p">(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">)</span>

<span class="c1"># Show all created objects which is only RectangleOfLines</span>
<span class="n">show_all</span><span class="p">()</span>
</code></pre></div></td></tr></table></div>
<p>This gives the same sketch object as the one we created with RectangleOfLines. You might notice that we needed less information AND that this object will now be centered at the origin (x=0,y=0). All objects will normally be build by being centered as each object has an additional property called "alignt" which has as default the center option. So to make it truly equal we have to adjust it's placing.</p>
<h3 id="placing-with-align">Placing with "align"</h3>
<div class="highlight"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span></span><span class="normal"> 1</span>
<span class="normal"> 2</span>
<span class="normal"> 3</span>
<span class="normal"> 4</span>
<span class="normal"> 5</span>
<span class="normal"> 6</span>
<span class="normal"> 7</span>
<span class="normal"> 8</span>
<span class="normal"> 9</span>
<span class="normal">10</span>
<span class="normal">11</span>
<span class="normal">12</span>
<span class="normal">13</span>
<span class="normal">14</span>
<span class="normal">15</span>
<span class="normal">16</span></pre></div></td><td class="code"><div><pre><span></span><code><span class="c1"># Import ocp_vscode which is an addon to view the 3D model in VScode</span>
<span class="kn">from</span> <span class="nn">ocp_vscode</span> <span class="kn">import</span> <span class="o">*</span>
<span class="c1"># Import build123d library to be able to use build123 commands</span>
<span class="kn">from</span> <span class="nn">build123d</span> <span class="kn">import</span> <span class="o">*</span>

<span class="c1"># Define an x and y value for the rectangle</span>
<span class="n">x</span><span class="o">=</span><span class="mi">20</span>
<span class="n">y</span><span class="o">=</span><span class="mi">10</span>

<span class="c1"># Start the Sketch builder which creates 2D sketch objects</span>
<span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">RectangleAsSketch</span><span class="p">:</span>
  <span class="c1"># Create a Rectangle and change it&#39;s alignment property</span>
  <span class="n">Rectangle</span><span class="p">(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">,</span><span class="n">align</span><span class="o">=</span><span class="p">(</span><span class="n">Align</span><span class="o">.</span><span class="n">MIN</span><span class="p">,</span><span class="n">Align</span><span class="o">.</span><span class="n">MIN</span><span class="p">))</span>

<span class="c1"># Show all created objects which is only RectangleOfLines</span>
<span class="n">show_all</span><span class="p">()</span>
</code></pre></div></td></tr></table></div>
<p>The "align=" options you can choose from are:</p>
<ul>
<li>Align.MIN</li>
<li>Align.MAX</li>
<li>Align.CENTER</li>
</ul>
<p>You can use each of these options for one of the 2 paramters of the "align=" statement.</p>
<h3 id="placing-with-the-position-property-of-the-object">Placing with the position property of the object</h3>
<h3 id="placing-with-the-pos-command">Placing with the POS() command</h3>
<h3 id="other-options-to-create-a-rectangle-or-a-edged-2d-shape">Other options to create a rectangle or a edged 2D shape</h3>
<p>Other ways to create a rectangle is to use the Rectangle, Polygon,  RegularPolygon or Trapezoid.</p>
<p>See: Polygon</p>
<p>See: RegularPolygon</p>
<p>See: Trapezoid</p>
              
            </div>
          </div><footer>
    <div class="rst-footer-buttons" role="navigation" aria-label="Footer Navigation">
        <a href="../../1D%20Objects/1D%20Line/" class="btn btn-neutral float-left" title="1D Line"><span class="icon icon-circle-arrow-left"></span> Previous</a>
        <a href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/" class="btn btn-neutral float-right" title="Testtitle">Next <span class="icon icon-circle-arrow-right"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <!-- Copyright etc -->
  </div>

  Built with <a href="https://www.mkdocs.org/">MkDocs</a> using a <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>.
</footer>
          
        </div>
      </div>

    </section>

  </div>

  <div class="rst-versions" role="note" aria-label="Versions">
  <span class="rst-current-version" data-toggle="rst-current-version">
    
    
      <span><a href="../../1D%20Objects/1D%20Line/" style="color: #fcfcfc">&laquo; Previous</a></span>
    
    
      <span><a href="../../../Setup%20of%20the%20working%20enviroment/Foreword%20working%20environment/" style="color: #fcfcfc">Next &raquo;</a></span>
    
  </span>
</div>
    <script src="../../../js/jquery-3.6.0.min.js"></script>
    <script>var base_url = "../../..";</script>
    <script src="../../../js/theme_extra.js"></script>
    <script src="../../../js/theme.js"></script>
      <script src="../../../search/main.js"></script>
    <script>
        jQuery(function () {
            SphinxRtdTheme.Navigation.enable(true);
        });
    </script>

</body>
</html>
